### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GustavoFranzolin** [resurfaceio/insomnia-plugin#4]
Hello, I am trying to install this plugin and receiving the following message below, could you please help me?

"Failed to load plugin insomnia-plugin. Please contact the plugin author sharing the below stack trace to help them to ensure compatibility with the latest Insomnia."

```
Error: Cannot find module 'resurfaceio-logger'
Require stack:
- /home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js
- /snap/insomnia/290/resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)Error: Cannot find module 'resurfaceio-logger'
Require stack:
- /home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js
- /snap/insomnia/290/resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js:9:5)
    at Object.<anonymous> (/home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js:95:3)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at _traversePluginPath (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:83:7943)
    at async getPlugins (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:83:8939)
    at async st (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:1064:66521)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js:9:5)
    at Object.<anonymous> (/home/gustavo/snap/insomnia/290/.config/Insomnia/plugins/insomnia-plugin/src/plugin.js:95:3)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at _traversePluginPath (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:83:7943)
    at async getPlugins (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:83:8939)
    at async st (file:///snap/insomnia/290/resources/app.asar/mainWindow-CwAvrReO.js:1064:66521)
```

**Comment by monrax** [comment]
Hi there! Thank you for taking a look at our plugin.

It seems that your Insomnia instance can't find the dependencies for the plugin.

Could you remove the plugin and re-install it? In order to completely remove the plugin, just click the "Reveal Plugins Folder" button in the Insomnia Preferences, then delete the `insomnia-plugin-usage-logger` directory (or just `insomnia-plugin`, in your case) and its contents:

![image](https://github.com/user-attachments/assets/333cad5d-620a-4557-96f5-854dc42f30a2)
![image](https://github.com/user-attachments/assets/d1d14ceb-78c0-48ba-a286-32ca160b6cf2)

Or, if you are more comfortable with the terminal:

```
rm -rf ~/.config/Insomnia/plugins/insomnia-plugin
```

Finally, reinstall the plugin by following the current instructions:

![image](https://github.com/user-attachments/assets/f77274a8-1dda-484a-a3b4-c2b60bd07afa)

Be sure to close and re-open Insomnia after installing the plugin.

Please, let me know this works for you or if you need any further assistance. Happy to help 😄
